import express from 'express';
import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';
import pug from 'pug';


// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const app = express();
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: 'jekyllgdrive@jekyllgdrive-416407.iam.gserviceaccount.com',
  key: '-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCkf8cGLPWUrkqc\n7IZ3drpUPKKa12E9UfdrVBUNLTefH+/Nl8ZBfkRBF3BpOeqF0yCFvLeoRgAzMjm/\nV7/c1L6SOk/P7eE2cxrspOvzGGijsFLM2Pr+KoLBfkihrNRwc6esc/bjFXINLIBG\n+I5LdVkj5vRbMeJJyUkE2Ug6H2Ghg/FUlmWQefk7gv+1oExeBcFGrZV+l+1xD5hm\n/jZLnRyR5iDBoC3Drke9dm9dh0LRG1N3FQjMSyvmYTVNMQviwCZcZK3HFhKrZL9u\n3dOT1Qqyn4zF9qiyTsiVSBAGx/mW6dMM08+cHaDddMAahGBRxMe6DPnWw8xVihm4\npft8RFE9AgMBAAECggEABoRSzQcVDJie3c3BO84RLpSlx+O3/bveHptBNHL7fnsy\nq7uzT9vR4uoSWtmmFaEQkdPKsXWVsCS+SzsNkt2+L6D0d///bKhacCnn3uSmgpoF\nHonxeZ/Ga3MWeApwWR5WQNudDVzt/Lq4wBCi4uqDFBj9sPfOZ46ioEWzM5N6MYth\neA+lzAv3VZMLEsK/RBu0XnjVw5m2UJ1+Rw6BQrciBxHbi6Jo/4RVLsnPhDicqXji\nmCLgJouRv4Wb5DwJHWuNMvfGbopYKeVPIrnWwuijukU9bTtMTE0pZ4KrOH92qJtO\nwPKqYsFoeryTL4oU2H5TNcjxnUhAAKMSJyMzzaZJkQKBgQDb1u5YSlqmVSZwjjS5\ngJlEV0WEk8sBTUeT02LC1uCLPrMMiSXCMSw8YtbFx7F7bljfysolW9/yH4seuUMX\nx4paWF25sopwwY9TzYCwMYxC+PkidBxOIV4mni3Q00FrZoGlXsWcBxYeCUe9dQFY\nEnBdsRRS8smSHiTDlcZa+KANEQKBgQC/jo4KVhCOMF4zfDbTM2zxnuTxvcbzX9Kt\nX/KP9tR72YOLf24gYxzlRw1fx7RBq8cu2mLUbh/bRkGddBBy4/aEvadrg0pTC1Xv\n/MnIJk0JPm7R6+hzXTal319GDWTE/m9UsgMqMsKismPegNiD0fw7IUunRwZNb09A\nRpnI3baxbQKBgQChT7f6zyxvKsIXCzIDACr2q7cWDkCCxwsDnLO2VmfTpQFK7IPp\nV52m/busytgfwxuxsyLbgOv1xVGXDMf/deq+WmMDtM/C5zTdgEiygNjz968PqfVv\nGyrz2VOzDKDPRxtQlhcYY1bGWXbrvSRsVLNg/GP2bbKc5kOBxLAU5qTCkQKBgQCd\n1ehTu/aIMnJsGb1S6NyrejFKvwRfJGWDVbuXw9nw8pjhKG6lYQU+Jf1vHi34roHA\nqVElmFfHZWxLQIcNI6jMVzjL7bIgGwcEZ1YcBPMU2syVS7yM0hFlO1hVcFPHvZ4e\nO09ARfL5++MuQxwkAbHDRvv/KRaYV08Ftyafy4/tQQKBgGxk+33JPJj/G9olwRmi\n/8WfzO+OUVO1JAdIISNbPH/8yQj5TnOz6GezkNgwFi3YKvjkALDMQ0JagLfgKaQc\n1/FrIoZyEK62I5nsPBwPcqA0+UJIeBRs71kg4upvfVdf33QZUrMmWcj3JxJD7Qg6\nuqzDv6IGfDpO4rHYL0yrGOLL\n-----END PRIVATE KEY-----\n',
  scopes: [
    'https://www.googleapis.com/auth/spreadsheets',
  ],
});

// Set the view engine to Pug
// app.set('view engine', 'pug');
// app.set('views', './new_views'); // Specify the folder where your Pug templates are located
app.use(express.static('public')); // Assuming 'public' is your assets folder name


// Initialize the document
const doc = new GoogleSpreadsheet('1BsEIF91CGBQjni0O4XDIpMFsk1i9ldo0Rv6-meCa6Hc', serviceAccountAuth);

// Load the document properties and worksheets
await doc.loadInfo();
console.log(doc.title);

// Access a specific sheet
const sheet = doc.sheetsByIndex[0]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
console.log(sheet.title);
console.log(sheet.rowCount);

//
// const sheet = doc.sheetsByTitle["Harga hari ini"]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
// console.log(sheet.getRows());


// await sheet.loadCells('B2:F13');
// console.log(sheet.cellStats);

// // Read rows
// const rows = await sheet.getRows();
// console.log(rows[0].name); // logs the first row's name column

async function getCellData(range) {
  // await doc.useServiceAccountAuth(serviceAccountAuth);
  await doc.loadInfo();
  const sheet = doc.sheetsByIndex[0];
  await sheet.loadCells(range);
  // Create an array to hold cell values
  const cellData = [];

  // Retrieve cell values and add them to the array
  for (let row = 4; row <= 12; row++) {
    const rowData = [];
    for (let col = 2; col <= 5; col++) {
      const cell = sheet.getCell(row, col);
      rowData.push(cell.formattedValue);
    }
    cellData.push(rowData);
  }

  // Convert the array to a JSON object
  const jsonData = {
    cellData,
  };
  console.log(JSON.stringify(jsonData, null, 2));
  return jsonData;

}

app.get('/simulator', async (req, res) => {
  res.render('simulator')
});

app.get('/api/cellData', async (req, res) => {
  const jsonData = await getCellData('C2:F13');
  res.json(jsonData);  // Send cellData as JSON
});


//Render the index.pug template with the provided data
// app.get('/', async (req, res) => {
//   // const jsonData = await getCellData('C2:F13'); // Load your JSON data
//   const day = new Date().toLocaleDateString('id-ID', { weekday: 'long' });
//   const date = new Date().toLocaleDateString('id-ID');
//   res.render('index', { cellData: jsonData.cellData, day, date });
// });

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));