[build]
    publish = "public"
    functions = "netlify/functions"
    command = "npm install && npm start"
    node_bundler = "esbuild"

[dev]
    publish = "public"
    node_bundler = "esbuild"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[[redirects]]
    from = "/jual-beli-antar-emas-antam"
    to = "/index.html#gold-price"
    status = 301

[[redirects]]
    from = "/review"
    to = "https://g.page/r/CSqS7XFeYwogEBM/review"
    status = 301
