[build]
    publish = "public"
    functions = "netlify/functions"
    command = "npm install && npm start"
    node_bundler = "esbuild"

[dev]
    publish = "public"
    node_bundler = "esbuild"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200